# Generated by Django 4.1 on 2022-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csvapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
