# Generated by Django 4.1 on 2022-08-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csvapp", "0002_alter_amount_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
